#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
sh ~/.config/dunst/launch.sh &
sh ~/.config/polybar/launch.sh &
sh ~/.config/copyq/launch.sh &


bspc monitor DisplayPort-1 -d I II III IV V
bspc monitor HDMI-A-1 -d VI VII VIII IX X
bspc wm -O DisplayPort-1 HDMI-A-1

bspc config border_width         1
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
